### ISSUE TITLE
What is the PortcheckService for?

### ISSUE THREAD

**Issue by Kavex** [Guad/sm64o#13]
As far as I can tell the PortcheckService isn't used and with it's weird .csproj file it throws errors in the IDE.

Can you break this one down for me?

**Comment by Guad** [comment]
It's used to query whether one's ports are open. The port check service was supposed to be up at api.sm64o.com

**Comment by leafi** [comment]
hey, yep what @Guad says is correct... sorry i've been away for a week. really nasty flu, i've been bed-bound!

good to see we're open source now :)

**Comment by leafi** [comment]
See PR #15
